name: LeoCAD CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-windows:
    # if: ${{ false }} # uncomment to disable this job
    name: 'Build ${{ matrix.name }}'
    runs-on: ${{ matrix.runner-os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        runner-os: [ windows-2025, windows-11-arm ]
        platform: [ AMD64, ARM64 ]
        exclude:
          - runner-os: windows-2025
            platform: ARM64
          - runner-os: windows-11-arm
            platform: AMD64
        include:
          - runner-os: windows-2025
          - runner-os: windows-11-arm
          - platform: AMD64
            name: Windows 2025 AMD64
            host: ''
            arch: _64
            vca: X64
          - platform: ARM64
            name: Windows 11 ARM64
            host: _arm64
            arch: _arm64
            vca: ARM64
    steps:
    - name: Checkout Source
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Work Paths
      run: |
        Echo "LC_BUILD_BASE=$(resolve-path ..\)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        Echo "LC_BUILD_APPDIR=$(Join-Path (resolve-path ..\) 'appdir')" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        New-Item -Path ..\ -Name 'appdir' -ItemType 'directory'
    - name: Qt MSVC 2022 ${{ matrix.platform }} # path: ..\Qt\6.10.0\msvc2022_arm64\bin
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.10.0
        host: windows${{ matrix.host }}
        target: desktop
        modules: qt5compat
        arch: win64_msvc2022${{ matrix.arch }}
        dir: ${{ env.LC_BUILD_BASE }}
        cache: 'true'
        cache-key-prefix: install-qt
    - name: Cache Parts Library
      uses: actions/cache@v3
      id: cache-library
      with:
        path: ${{ env.LC_BUILD_APPDIR }}\library.bin
        key: library-25.08
    - name: Download Parts Library
      if: steps.cache-library.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        curl https://github.com/leozide/leocad/releases/download/v23.03/Library-25.08.zip -Lo library.zip
        unzip library.zip -d ${{ env.LC_BUILD_APPDIR }}
    - name: Cache POV-Ray
      uses: actions/cache@v3
      id: cache-povray
      with:
        path: ${{ env.LC_BUILD_APPDIR }}\povconsole32-sse2.exe
        key: povray-20.03
    - name: Download POV-Ray
      if: steps.cache-povray.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        :: the x86 version of POVRay will work on ARM64 in emulation mode but will be less efficient.
        curl https://github.com/leozide/povray/releases/download/continuous/povconsole32-sse2.exe -Lo ${{ env.LC_BUILD_APPDIR }}\povconsole32-sse2.exe
    - name: Install NSIS with EnVar plugin # missing in Windows 2025 but pre-installed in windows-11-arm
      if: ${{ matrix.runner-os == 'windows-2025' && matrix.platform == 'AMD64' }}
      uses: repolevedavaj/install-nsis@v1.0.3
      with:
        nsis-version: 3.11
    - name: Build ${{ matrix.name }}
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.platform }}
        set "CONFIG_ARGS=CONFIG+=Release CONFIG-=debug_and_release"
        set "MAKE_ARGS=-c -f Makefile"
        qmake -v
        qmake %CONFIG_ARGS%
        nmake %MAKE_ARGS%
    - name: Stage ${{ matrix.name }}
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.platform }}
        copy docs\readme.md ${{ env.LC_BUILD_APPDIR }}\readme.txt
        copy build\release\leocad.exe ${{ env.LC_BUILD_APPDIR }}
        windeployqt ${{ env.LC_BUILD_APPDIR }}\leocad.exe
    - name: Check ${{ matrix.name }}
      if: ${{ matrix.runner-os == 'windows-11-arm' }}
      id: check
      shell: cmd
      run: |
        copy resources\8464.ldr ${{ env.LC_BUILD_BASE }}\8464.mpd
        cd ${{ env.LC_BUILD_BASE }}
        ${{ env.LC_BUILD_APPDIR }}\leocad.exe -i 8464.png -l ${{ env.LC_BUILD_APPDIR }}\library.bin 8464.mpd
    - name: Package ${{ matrix.name }}
      if: success() || ( failure() && steps.check.outcome == 'failure' )
      shell: cmd
      run: |
        copy tools\setup\leocad.nsi ${{ env.LC_BUILD_BASE }}
        copy tools\setup\setup.ico ${{ env.LC_BUILD_BASE }}
        git rev-parse --short HEAD > version.txt
        set /p VERSION= < version.txt
        tar.exe -a -c -f ${{ env.LC_BUILD_BASE }}\symbols-${{ matrix.platform }}-%VERSION%.zip build\release\leocad.exe build\release\leocad.pdb
        cd ${{ env.LC_BUILD_BASE }}
        "C:\Program Files (x86)\NSIS\makensis.exe" /V4 /D${{ matrix.vca }} "/XOutFile LeoCAD-Windows-${{ matrix.platform }}-%VERSION%.exe" leocad.nsi
    - name: Deploy ${{ matrix.name }}
      if: success() || ( failure() && steps.check.outcome == 'failure' )
      shell: cmd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl https://github.com/probonopd/uploadtool/raw/master/upload.sh -Lo upload.sh
        set UPLOADTOOL_ISPRERELEASE=1
        if not defined GITHUB_HEAD_REF (bash upload.sh ${{ env.LC_BUILD_BASE }}/LeoCAD*.exe ${{ env.LC_BUILD_BASE }}/symbols*.zip)

  build-ubuntu:
    if: ${{ false }} # uncomment to disable this job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4  
      with:
        cache: 'true'
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: Generate Makefile
      run: qmake PREFIX=/usr
    - name: Build
      run: make -j ${{ steps.cpu-cores.outputs.count }}

  build-macos:
    if: ${{ false }} # uncomment to disable this job
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3  
      with:
        cache: 'true'
    - name: Cache Library
      uses: actions/cache@v3
      id: cache-library
      with:
        path: library.bin
        key: library-25.08
    - name: Download Library
      if: steps.cache-library.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/leozide/leocad/releases/download/v23.03/Library-25.08.zip -O library.zip
        unzip library.zip
    - name: Cache POV-Ray
      uses: actions/cache@v3
      id: cache-povray
      with:
        path: povray
        key: povray-20.03
    - name: Download POV-Ray
      if: steps.cache-povray.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/leozide/povray/releases/download/continuous/povray
        chmod +x povray
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/leozide/leocad/commits/master -o repo.txt
        echo < repo.txt
        echo export REMOTE=$(grep -Po '(?<=: \")(([a-z0-9])\w+)(?=\")' -m 1 repo.txt)
        export REMOTE=$(grep -Po '(?<=: \")(([a-z0-9])\w+)(?=\")' -m 1 repo.txt)
        echo $REMOTE        
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: Generate Makefile
      run: qmake -early QMAKE_DEFAULT_LIBDIRS=$(xcrun -show-sdk-path)/usr/lib PREFIX=/usr
    - name: Build
      run: make -j ${{ steps.cpu-cores.outputs.count }}
